name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Start xcodebuild test
      run: xcodebuild clean build -project BLEUnlock.xcodeproj -scheme BLEUnlock CODE_SIGNING_ALLOWED=NO
